# Generated by Django 5.2.9 on 2026-03-11 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'date')},
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='evening_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='morning_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='start_time',
        ),
    ]
