# Generated by Django 5.2.9 on 2026-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctoravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
